Creating "next.config.js".
-- Server Error
Error: Invalid src prop (https://images.prismic.io/next-js-prismic-cms/90909938-c0a9-4c15-b5af-2640cfdb7842_second-post-image.jpg?auto=compress,format) on `next/image`, hostname "images.prismic.io" is not configured under images in your `next.config.js`
See more info: https://nextjs.org/docs/messages/next-image-unconfigured-host

- Creating "next.config.js" to fix issue above:
º With the content here "https://github.com/vercel/next.js/blob/canary/examples/image-component/next.config.js".
º Or as per link (in 'see more info') very above "https://nextjs.org/docs/messages/next-image-unconfigured-host".
º Needed to 'restart the server manually' (ctrl + c) after for changes to take effect.
- Adding 2 more posts within Prismic CMS.